import core, { SYNC } from "./core";
import redis from "./adapters/redis";
import amqp from "./adapters/amqp";
import nats from "./adapters/nats";
import { SyncOptions } from "./types";
declare const init: (options: SyncOptions) => import("./types").SyncFunction;
export default init;
export { init, core, redis, amqp, nats, SYNC };
export declare const rabbitmq: (config: import("./types").AmqpSyncOptions) => (app: import("@feathersjs/feathers").Application) => void;
export * from "./types";
